name: AntiWeather
version: '${project.version}'
main: com.froostysnoowman.aw.Main
api-version: 1.16
authors: [Someone]
description: AntiWeather Plugin
website: www.spigotmc.org
commands:
  fly:
    description: Toggle your flight
    usage: /<command>